name: Build & publish daily forecast

on:
  schedule:
    # 10:00 UTC  ≈ 07:00 BRT
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install deps & build site
      run: |
        npm ci
        npm run build            # gera public/index.html

    # ⬇️ VERSÃO NOVA, sem advertência
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # obrigatórios
      id-token: write   #  ↑
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
